[book]
authors = ["ysykzheng"]
language = "en"
multilingual = false
src = "src"
title = "AI for Business Writing: Techniques and Strategies for Creating More Effective Communications with Technology"
